// Parent vocabulary data — every English Coding curriculum.
// Each term: t = term, d = plain-English definition, w = week, ex = SUPER simple code example.
// All English (used for printable PDF vocab lists parents can send / keep).

export const CURRICULA = [
  // ───────────────────────── PYTHON / REPLIT ─────────────────────────
  {
    code: "RS001", title: "Text Adventure Game", icon: "📜", track: "Replit / Python",
    blurb: "Choose-your-own-adventure built in Python.",
    terms: [
      { t: "variable", d: "a named box that holds a value", w: "W1", ex: 'name = "Sam"' },
      { t: "input()", d: "function that reads what the user types", w: "W1", ex: 'door = input("Left or right? ")' },
      { t: "f-string", d: "a string with variables placed inside { }", w: "W1", ex: 'print(f"Hi {name}!")' },
      { t: "list", d: "an ordered group of values in [ ]", w: "W2", ex: 'paths = ["cave", "river"]' },
      { t: "index", d: "the number that locates an item in a list", w: "W2", ex: 'paths[0]   # "cave"' },
      { t: ".strip()", d: "remove blank space from the start and end", w: "W3", ex: '" hi ".strip()   # "hi"' },
      { t: ".lower()", d: "change all letters to lowercase", w: "W3", ex: '"YES".lower()   # "yes"' },
      { t: "in", d: "tests whether a value is inside a list", w: "W4", ex: '"cave" in paths   # True' },
      { t: "not in", d: "tests whether a value is missing from a list", w: "W4", ex: '"sky" not in paths   # True' },
      { t: "while", d: "repeat as long as a condition is true", w: "W4", ex: "while alive:\n    play()" },
      { t: "if / elif / else", d: "a three-way branch on conditions", w: "W5", ex: 'if x == 1:\n    ...\nelse:\n    ...' },
      { t: "decision tree", d: "a map of choices and their results", w: "W6", ex: 'if choice == "fight": battle()' },
      { t: "action list", d: "list of valid things the player can do", w: "W6", ex: 'actions = ["go", "take", "use"]' },
      { t: "import", d: "load a Python module so you can use it", w: "W7", ex: "import random" },
      { t: "random.choice", d: "pick one item from a list at random", w: "W7", ex: "random.choice(paths)" },
      { t: "parallel lists", d: "two lists where the same index pairs them", w: "W8", ex: "questions[0] -> answers[0]" },
      { t: "and / or", d: "combine two conditions into one", w: "W8", ex: "if has_key and door_open:" },
    ],
  },
  {
    code: "RS002", title: "Pokémon Pokédex App", icon: "🔴", track: "Replit / Python",
    blurb: "Interactive Pokédex with dictionaries and battles.",
    terms: [
      { t: "input()", d: "function that reads what the user types", w: "W1", ex: 'name = input("Trainer name? ")' },
      { t: "variable", d: "a named box that holds a value", w: "W1", ex: "hp = 100" },
      { t: "f-string", d: "a string with variables inside { }", w: "W1", ex: 'print(f"{name} caught it!")' },
      { t: "list", d: "an ordered group of values in [ ]", w: "W2", ex: 'team = ["Pikachu"]' },
      { t: "index", d: "the number that locates an item in a list", w: "W2", ex: "team[0]" },
      { t: ".append()", d: "add an item to the end of a list", w: "W2", ex: 'team.append("Eevee")' },
      { t: ".strip()", d: "remove blank space from start and end", w: "W3", ex: '" go ".strip()' },
      { t: ".lower()", d: "change all letters to lowercase", w: "W3", ex: '"FIRE".lower()' },
      { t: "case sensitive", d: "'A' and 'a' count as different", w: "W3", ex: '"A" == "a"   # False' },
      { t: "if / else", d: "a two-way branch on a condition", w: "W4", ex: "if hp > 0:\n    ...\nelse:\n    ..." },
      { t: "in / not in", d: "test whether a value is inside a list", w: "W4", ex: '"Pikachu" in team' },
      { t: "while", d: "repeat as long as a condition is true", w: "W4", ex: "while hp > 0:\n    fight()" },
      { t: "dict", d: "a key→value mapping written in { }", w: "W5", ex: 'p = {"name": "Pikachu", "hp": 35}' },
      { t: "key", d: "the label used to look up a value", w: "W5", ex: 'p["name"]' },
      { t: "value", d: "the data stored under a key", w: "W5", ex: 'p["hp"]   # 35' },
      { t: "KeyError", d: "you asked for a key that isn't there", w: "W5", ex: 'p["age"]   # KeyError' },
      { t: "def", d: "the keyword that defines a function", w: "W6", ex: "def attack():\n    ..." },
      { t: "parameter", d: "an input the function expects", w: "W6", ex: "def attack(power):" },
      { t: "return", d: "the value the function gives back", w: "W6", ex: "return damage" },
      { t: "import", d: "load a Python module to use it", w: "W7", ex: "import random" },
      { t: "random.choice", d: "pick one list item at random", w: "W7", ex: "random.choice(team)" },
      { t: "randint", d: "a random whole number between two ends", w: "W7", ex: "random.randint(1, 6)" },
      { t: "game loop", d: "the while-true that keeps the game running", w: "W8", ex: "while True:\n    turn()" },
      { t: "game state", d: "the variables describing what's happening now", w: "W8", ex: "turn = 1; winner = None" },
      { t: "end condition", d: "what makes the loop stop", w: "W8", ex: "if hp <= 0: break" },
    ],
  },
  {
    code: "RS003", title: "Pygame Shooter Game", icon: "🎮", track: "Replit / Python",
    blurb: "First graphics game — pygame, coordinates, loops.",
    terms: [
      { t: "pygame.init()", d: "wake up the pygame engine", w: "W1", ex: "pygame.init()" },
      { t: "display.set_mode", d: "open a game window of a given size", w: "W1", ex: "pygame.display.set_mode((800, 600))" },
      { t: "event loop", d: "the loop that checks for clicks and keys", w: "W1", ex: "for e in pygame.event.get():" },
      { t: "QUIT event", d: "the signal that the user closed the window", w: "W1", ex: "if e.type == pygame.QUIT:" },
      { t: "surface", d: "any drawable image in pygame", w: "W2", ex: "screen = pygame.display.set_mode(...)" },
      { t: "blit", d: "paste one surface onto another", w: "W2", ex: "screen.blit(gun, (x, y))" },
      { t: "rect", d: "a rectangle holding x, y, width, height", w: "W2", ex: "r = pygame.Rect(0, 0, 50, 50)" },
      { t: "def", d: "the keyword that defines a function", w: "W3", ex: "def draw_gun():\n    ..." },
      { t: "parameter", d: "an input the function expects", w: "W3", ex: "def draw_gun(x):" },
      { t: "call site", d: "the place where you use the function", w: "W3", ex: "draw_gun(100)" },
      { t: "get_pressed", d: "which keys are held down right now", w: "W4", ex: "keys = pygame.key.get_pressed()" },
      { t: "K_LEFT / K_RIGHT", d: "key constants for the arrow keys", w: "W4", ex: "if keys[pygame.K_LEFT]:" },
      { t: "velocity", d: "how fast something moves per frame", w: "W4", ex: "x += velocity" },
      { t: "clamp", d: "force a value to stay inside a range", w: "W5", ex: "x = max(0, min(x, 800))" },
      { t: "min / max", d: "smallest / largest allowed value", w: "W5", ex: "max(0, x)" },
      { t: "boundary", d: "the edge of the playable area", w: "W5", ex: "if x > screen_width: x = screen_width" },
      { t: "for loop", d: "repeat once per item", w: "W6", ex: "for i in range(5):\n    shoot()" },
      { t: "range()", d: "a sequence of numbers from start to end−1", w: "W6", ex: "range(3)   # 0,1,2" },
      { t: "iteration", d: "one pass through the loop", w: "W6", ex: "for bullet in bullets:" },
      { t: "modular code", d: "code split into small reusable pieces", w: "W7", ex: "def move(): ...\ndef draw(): ..." },
      { t: "single responsibility", d: "one function does one thing", w: "W7", ex: "def fire_bullet(): ..." },
      { t: "naming", d: "good names describe the action", w: "W7", ex: "def reset_score(): ..." },
      { t: "score", d: "the number that tracks player success", w: "W8", ex: "score += 1" },
      { t: "game over", d: "the state when the player has lost", w: "W8", ex: "if lives == 0: game_over = True" },
      { t: "frame rate", d: "how many frames are drawn per second", w: "W8", ex: "clock.tick(60)" },
    ],
  },
  {
    code: "RS004", title: "Platformer Game", icon: "🌟", track: "Replit / Python",
    blurb: "Side-scroller with gravity and collisions.",
    terms: [
      { t: "pygame.init()", d: "wake up the pygame engine", w: "W1", ex: "pygame.init()" },
      { t: "display.set_mode", d: "open a game window of a given size", w: "W1", ex: "pygame.display.set_mode((640, 480))" },
      { t: "clock.tick(60)", d: "limit the game to 60 frames per second", w: "W1", ex: "clock.tick(60)" },
      { t: "sprite", d: "a movable character or object", w: "W2", ex: "player = pygame.Rect(50, 50, 32, 32)" },
      { t: "rect", d: "a rectangle that tracks position and size", w: "W2", ex: "player.x += 5" },
      { t: "delta", d: "the amount to move per frame", w: "W2", ex: "dx = 5; player.x += dx" },
      { t: "gravity", d: "a constant downward pull each frame", w: "W3", ex: "vel_y += gravity" },
      { t: "velocity_y", d: "the current vertical speed", w: "W3", ex: "player.y += vel_y" },
      { t: "jump impulse", d: "a sudden upward velocity from a jump", w: "W3", ex: "vel_y = -12" },
      { t: "ground", d: "the surface that stops downward motion", w: "W3", ex: "if player.y > 400: player.y = 400" },
      { t: "collision", d: "two rectangles overlap", w: "W4", ex: "player.colliderect(coin)" },
      { t: "colliderect", d: "pygame method that detects overlap", w: "W4", ex: "if a.colliderect(b):" },
      { t: "platform", d: "a surface the player can stand on", w: "W4", ex: "platforms = [pygame.Rect(...)]" },
      { t: "level", d: "the layout of one stage", w: "W5", ex: 'level = ["..#..", "#####"]' },
      { t: "tile", d: "one piece of a level grid", w: "W5", ex: 'if cell == "#": draw_block()' },
      { t: "coordinates", d: "the (x, y) location on screen", w: "W5", ex: "pos = (x, y)" },
      { t: "collectible", d: "an item the player picks up", w: "W6", ex: "coins = [pygame.Rect(...)]" },
      { t: "score", d: "the number that tracks progress", w: "W6", ex: "score += 10" },
      { t: "remove", d: "delete an item from a list once collected", w: "W6", ex: "coins.remove(coin)" },
      { t: "enemy", d: "a sprite that hurts the player on contact", w: "W7", ex: "if player.colliderect(enemy): die()" },
      { t: "game state", d: "playing / dead / won — the current mode", w: "W7", ex: 'state = "playing"' },
      { t: "respawn", d: "put the player back at the start", w: "W7", ex: "player.x, player.y = 50, 50" },
      { t: "level transition", d: "moving from one level to the next", w: "W8", ex: "level_index += 1" },
      { t: "level list", d: "list of level layouts to load in order", w: "W8", ex: "levels = [level1, level2]" },
      { t: "polish", d: "final touch-ups before shipping", w: "W8", ex: "# add sound, fix bugs" },
    ],
  },

  // ───────────────────────── WEB DEV ─────────────────────────
  {
    code: "WEB001", title: "HTML + CSS Basics", icon: "🎨", track: "Web Development",
    blurb: "Style your first website.",
    terms: [
      { t: "tag", d: "the angle-bracket label that names an element", w: "W1", ex: "<h1>Title</h1>" },
      { t: "element", d: "an open tag, its content, and a close tag", w: "W1", ex: "<p>Hello</p>" },
      { t: "attribute", d: "extra info inside a tag (src, href)", w: "W1", ex: '<img src="cat.png">' },
      { t: "nesting", d: "putting one element inside another", w: "W1", ex: "<ul><li>Item</li></ul>" },
      { t: "selector", d: "which element the style applies to", w: "W2", ex: "p { color: red; }" },
      { t: "property", d: "what you're changing (color, font-size)", w: "W2", ex: "color: blue;" },
      { t: "value", d: "the new setting for the property", w: "W2", ex: "font-size: 20px;" },
      { t: "hex code", d: "a 6-digit color like #ff7849", w: "W2", ex: "color: #ff7849;" },
      { t: "padding", d: "space INSIDE the box, around content", w: "W3", ex: "padding: 16px;" },
      { t: "margin", d: "space OUTSIDE the box, between boxes", w: "W3", ex: "margin: 24px;" },
      { t: "border", d: "the line at the edge of the box", w: "W3", ex: "border: 2px solid black;" },
      { t: "box-sizing", d: "whether width includes padding or not", w: "W3", ex: "box-sizing: border-box;" },
      { t: "flex container", d: "the parent that arranges children in a row", w: "W4", ex: "display: flex;" },
      { t: "justify-content", d: "spacing along the main axis", w: "W4", ex: "justify-content: center;" },
      { t: "align-items", d: "spacing along the cross axis", w: "W4", ex: "align-items: center;" },
      { t: "gap", d: "space between flex items", w: "W4", ex: "gap: 12px;" },
      { t: "hero section", d: "the big banner at the top of a page", w: "W5", ex: '<section class="hero">' },
      { t: "background-image", d: "a CSS image set behind an element", w: "W5", ex: "background-image: url(bg.jpg);" },
      { t: "alt text", d: "description of an image for screen readers", w: "W5", ex: '<img alt="A red car">' },
      { t: "media query", d: "CSS that applies only at certain sizes", w: "W6", ex: "@media (max-width: 600px) { ... }" },
      { t: "breakpoint", d: "the width where the layout changes", w: "W6", ex: "max-width: 768px" },
      { t: "viewport", d: "the visible area of the browser window", w: "W6", ex: '<meta name="viewport" ...>' },
      { t: ":hover", d: "style applied when the mouse is over it", w: "W7", ex: "button:hover { color: red; }" },
      { t: "transition", d: "a smooth change between two states", w: "W7", ex: "transition: 0.3s;" },
      { t: "transform", d: "move, rotate, or scale an element", w: "W7", ex: "transform: scale(1.1);" },
      { t: "layout", d: "the overall arrangement of sections", w: "W8", ex: "header / main / footer" },
      { t: "hierarchy", d: "what looks most important to the eye", w: "W8", ex: "<h1> bigger than <p>" },
    ],
  },
  {
    code: "WEB002", title: "JavaScript", icon: "⚡", track: "Web Development",
    blurb: "Bring pages to life with code.",
    terms: [
      { t: "console.log", d: "print a message to the browser console", w: "W1", ex: 'console.log("hi")' },
      { t: "script tag", d: "<script>…</script> — runs JS in HTML", w: "W1", ex: "<script>alert(1)</script>" },
      { t: "statement", d: "one instruction ending with a semicolon", w: "W1", ex: "let x = 5;" },
      { t: "let / const", d: "declare a variable (const can't change)", w: "W2", ex: 'const name = "Sam";' },
      { t: "DOM", d: "the tree of elements built from the HTML", w: "W2", ex: "document.body" },
      { t: "querySelector", d: "find one element by CSS selector", w: "W2", ex: 'document.querySelector("#title")' },
      { t: "textContent", d: "the text inside an element", w: "W2", ex: 'el.textContent = "New!"' },
      { t: "event", d: "something that happens (click, keypress)", w: "W3", ex: '"click"' },
      { t: "addEventListener", d: "run a function when an event fires", w: "W3", ex: 'btn.addEventListener("click", go)' },
      { t: "callback", d: "the function passed in to run later", w: "W3", ex: "setTimeout(go, 1000)" },
      { t: "input element", d: "<input> tag the user types into", w: "W4", ex: '<input id="name">' },
      { t: ".value", d: "the current text in an input field", w: "W4", ex: "input.value" },
      { t: "submit", d: "the action of sending a form", w: "W4", ex: 'form.addEventListener("submit", ...)' },
      { t: "if / else if / else", d: "a three-way branch on a condition", w: "W5", ex: "if (x > 0) { ... } else { ... }" },
      { t: "=== / !==", d: "strict equal / strict not equal", w: "W5", ex: '5 === "5"   // false' },
      { t: "boolean", d: "a value that is either true or false", w: "W5", ex: "let done = true;" },
      { t: "array", d: "an ordered list of values in [ ]", w: "W6", ex: "let nums = [1, 2, 3];" },
      { t: "for loop", d: "repeat code a fixed number of times", w: "W6", ex: "for (let i=0; i<3; i++) {}" },
      { t: ".forEach", d: "run a function once per array item", w: "W6", ex: "nums.forEach(n => console.log(n))" },
      { t: "function", d: "a reusable block of code", w: "W7", ex: "function greet() { ... }" },
      { t: "parameter", d: "an input the function expects", w: "W7", ex: "function greet(name) { ... }" },
      { t: "return", d: "the value the function gives back", w: "W7", ex: "return total;" },
      { t: "arrow function", d: "short syntax: () => { … }", w: "W7", ex: "const add = (a,b) => a+b;" },
      { t: "state", d: "the data describing what's on screen now", w: "W8", ex: "let score = 0;" },
      { t: "render", d: "update the DOM to match the state", w: "W8", ex: "el.textContent = score;" },
      { t: "event-driven", d: "code that reacts to user actions", w: "W8", ex: "on click → update" },
    ],
  },
  {
    code: "WEB003", title: "Portfolio Site", icon: "🚀", track: "Web Development",
    blurb: "Build and deploy your own site.",
    terms: [
      { t: "information architecture", d: "how content is grouped and ordered", w: "W1", ex: "Home → About → Work" },
      { t: "wireframe", d: "a rough sketch of a page layout", w: "W1", ex: "boxes on paper" },
      { t: "section", d: "a named block of related content", w: "W1", ex: "<section id='about'>" },
      { t: "semantic HTML", d: "tags that describe meaning", w: "W2", ex: "<header> <nav> <main>" },
      { t: "header / footer", d: "top and bottom landmarks of a page", w: "W2", ex: "<footer>© 2026</footer>" },
      { t: "nav", d: "a navigation links group", w: "W2", ex: "<nav><a href='#'>Home</a></nav>" },
      { t: "design tokens", d: "named colors/fonts/spacing in variables", w: "W3", ex: "--brand: #ff7849;" },
      { t: "CSS variables", d: "--name: value, reusable everywhere", w: "W3", ex: "color: var(--brand);" },
      { t: "consistency", d: "the same look across every page", w: "W3", ex: "reuse the same classes" },
      { t: "hero section", d: "the big banner at the top of a page", w: "W4", ex: '<section class="hero">' },
      { t: "CTA", d: "call-to-action — the main button", w: "W4", ex: '<a class="btn">Hire me</a>' },
      { t: "about section", d: "a short bio that introduces you", w: "W4", ex: "<section id='about'>" },
      { t: "grid", d: "a rows-and-columns layout in CSS", w: "W5", ex: "display: grid;" },
      { t: "card", d: "a small box that previews one project", w: "W5", ex: '<div class="card">' },
      { t: "thumbnail", d: "a small preview image", w: "W5", ex: '<img class="thumb">' },
      { t: "color scheme", d: "the set of colors used together", w: "W6", ex: "--bg / --text / --accent" },
      { t: "prefers-color-scheme", d: "browser hint for light/dark", w: "W6", ex: "@media (prefers-color-scheme: dark)" },
      { t: "toggle", d: "a button that switches two states", w: "W6", ex: "dark ↔ light" },
      { t: "form", d: "a set of inputs to collect user data", w: "W7", ex: "<form>...</form>" },
      { t: "smooth scroll", d: "animated scrolling between sections", w: "W7", ex: "scroll-behavior: smooth;" },
      { t: "anchor link", d: "a link that jumps to an id on the page", w: "W7", ex: '<a href="#about">' },
      { t: "hosting", d: "the service that serves your site", w: "W8", ex: "GitHub Pages / Netlify" },
      { t: "deploy", d: "push your site live to the internet", w: "W8", ex: "git push" },
      { t: "domain", d: "the address visitors type", w: "W8", ex: "mysite.com" },
    ],
  },

  // ───────────────────────── AI CODING ─────────────────────────
  {
    code: "AI001", title: "AI Coding with Replit Agent", icon: "🤖", track: "AI Coding",
    blurb: "Build apps by talking to AI.",
    terms: [
      { t: "prompt", d: "the instruction you give the AI", w: "W1", ex: '"Make a to-do list app"' },
      { t: "specificity", d: "the more concrete, the better the answer", w: "W1", ex: '"red button, top-right"' },
      { t: "scope", d: "how much you ask for in one prompt", w: "W1", ex: "one feature at a time" },
      { t: "context", d: "background info the AI needs", w: "W2", ex: '"This is a school app for kids"' },
      { t: "constraint", d: "a rule the AI must follow", w: "W2", ex: '"Use only Python"' },
      { t: "expected output", d: "what you want back, said upfront", w: "W2", ex: '"Return a CSV file"' },
      { t: "few-shot", d: "showing examples of what you want", w: "W3", ex: '"Like this: ..."' },
      { t: "anchor example", d: "one sample answer that sets the pattern", w: "W3", ex: '"Format: Name - Age"' },
      { t: "explicit", d: "say it plainly — don't make AI guess", w: "W3", ex: '"Always add comments"' },
      { t: "decomposition", d: "breaking one big problem into steps", w: "W4", ex: "1) form 2) save 3) show" },
      { t: "milestone", d: "a checkpoint you verify before moving on", w: "W4", ex: '"First, just the layout"' },
      { t: "scope creep", d: "asking for too much in one prompt", w: "W4", ex: "10 features at once ✗" },
      { t: "iterate", d: "improve through repeated small changes", w: "W5", ex: '"Now make it bigger"' },
      { t: "refine", d: "make a working answer better", w: "W5", ex: '"Same, but blue"' },
      { t: "revert", d: "go back to a previous working version", w: "W5", ex: "undo last change" },
      { t: "expected vs actual", d: "what should happen vs what does", w: "W6", ex: '"Should add, but it multiplies"' },
      { t: "trace", d: "the error path the program took", w: "W6", ex: "read the red error text" },
      { t: "reproduce", d: "make the bug happen on demand", w: "W6", ex: '"Click twice → it crashes"' },
      { t: "annotate", d: "add comments that explain the code", w: "W7", ex: "# this saves the file" },
      { t: "explain back", d: "describe the code in your own words", w: "W7", ex: '"This loop counts items"' },
      { t: "ownership", d: "knowing your code well enough to change it", w: "W7", ex: "you can edit it yourself" },
      { t: "MVP", d: "minimum viable product — smallest useful version", w: "W8", ex: "just login + list" },
      { t: "ship", d: "release something real to real users", w: "W8", ex: "share the live link" },
      { t: "retrospective", d: "review what worked and what didn't", w: "W8", ex: "what to do better next" },
    ],
  },

  // ───────────────────────── PYTHON BOOTCAMP · 100 DAYS ─────────────────────────
  {
    code: "BC001", title: "Python Foundations", icon: "🐍", track: "Python Bootcamp · 100 Days",
    blurb: "Days 1–16. Variables → OOP intro.",
    terms: [
      { t: "print()", d: "show text on the screen", w: "W1", ex: 'print("Hello")' },
      { t: "string", d: "text wrapped in quotes", w: "W1", ex: '"Band Name"' },
      { t: "input()", d: "read what the user types", w: "W1", ex: 'name = input("Name? ")' },
      { t: "int() / float()", d: "turn text into a whole / decimal number", w: "W2", ex: 'int("12")   # 12' },
      { t: "round()", d: "round a number to fewer decimals", w: "W2", ex: "round(3.14159, 2)" },
      { t: "f-string", d: "a string with variables inside { }", w: "W2", ex: 'f"Total: {bill}"' },
      { t: "if / elif / else", d: "choose a path based on a condition", w: "W3", ex: 'if age >= 18: ...' },
      { t: "comparison operators", d: "compare two values (>, <, ==)", w: "W3", ex: "score > 50" },
      { t: "logical and / or", d: "combine two conditions", w: "W3", ex: "if a and b:" },
      { t: "list", d: "an ordered group of values in [ ]", w: "W4", ex: 'moves = ["rock", "paper"]' },
      { t: "random module", d: "Python tool for random numbers/choices", w: "W4", ex: "import random" },
      { t: "random.randint", d: "a random whole number between two ends", w: "W4", ex: "random.randint(0, 2)" },
      { t: "for loop", d: "repeat once per item or count", w: "W5", ex: "for i in range(8):" },
      { t: "range()", d: "a sequence of numbers", w: "W5", ex: "range(5)   # 0..4" },
      { t: ".append()", d: "add an item to the end of a list", w: "W5", ex: "chars.append(letter)" },
      { t: "function (def)", d: "a named, reusable block of code", w: "W6", ex: "def greet():\n    print('Hi')" },
      { t: "argument", d: "the value you pass into a function", w: "W6", ex: "greet('Sam')" },
      { t: "indentation", d: "spaces that show what's inside a block", w: "W6", ex: "def f():\n    return 1" },
      { t: "while loop", d: "repeat as long as a condition is true", w: "W7", ex: "while not won:\n    guess()" },
      { t: "string slicing", d: "take part of a string by position", w: "W7", ex: 'word[0:3]' },
      { t: "modulo (%)", d: "the remainder after division", w: "W8", ex: "7 % 3   # 1" },
      { t: ".index()", d: "find the position of an item", w: "W8", ex: 'alpha.index("c")' },
      { t: "dictionary", d: "a key→value mapping in { }", w: "W9", ex: '{"bid": 100}' },
      { t: "key / value", d: "label and the data stored under it", w: "W9", ex: 'bids["Sam"] = 50' },
      { t: "nested dictionary", d: "a dictionary inside a dictionary", w: "W10", ex: '{"latte": {"water": 200}}' },
      { t: "type casting", d: "convert one data type to another", w: "W10", ex: "float(amount)" },
      { t: "return value", d: "the result a function hands back", w: "W11", ex: "return total" },
      { t: "sum()", d: "add up all numbers in a list", w: "W11", ex: "sum([5, 3, 2])" },
      { t: "scope", d: "where a variable can be seen/used", w: "W12", ex: "local vs global" },
      { t: "global", d: "use/modify a top-level variable inside a function", w: "W12", ex: "global score" },
      { t: "traceback", d: "the error report Python prints", w: "W13", ex: "IndexError: list index..." },
      { t: "debugging", d: "finding and fixing mistakes", w: "W13", ex: "print(x) to inspect" },
      { t: "game loop", d: "the while-true that runs the game", w: "W14", ex: "while playing:" },
      { t: "data structure", d: "an organized way to hold data", w: "W15", ex: "menu = {...}" },
      { t: "class", d: "a blueprint for making objects", w: "W16", ex: "class Quiz:" },
      { t: "object", d: "one thing built from a class", w: "W16", ex: "q = Quiz()" },
      { t: "__init__", d: "the setup method that runs on creation", w: "W16", ex: "def __init__(self):" },
    ],
  },
  {
    code: "BC002", title: "OOP & Games", icon: "🎮", track: "Python Bootcamp · 100 Days",
    blurb: "Days 17–32. Tkinter, Turtle, Snake, Pong, Pomodoro.",
    terms: [
      { t: "class", d: "a blueprint for making objects", w: "W1", ex: "class Question:" },
      { t: "attribute", d: "a variable that belongs to an object", w: "W1", ex: "self.text = text" },
      { t: "method", d: "a function that belongs to an object", w: "W1", ex: "def check(self):" },
      { t: "self", d: "the object the method is working on", w: "W1", ex: "self.score += 1" },
      { t: "instance", d: "one object made from a class", w: "W2", ex: "tim = Turtle()" },
      { t: "method call", d: "running a method on an object", w: "W2", ex: "tim.forward(100)" },
      { t: "object state", d: "the current values of an object", w: "W3", ex: "self.x, self.y" },
      { t: "event listener", d: "code that waits for a key/click", w: "W3", ex: "screen.onkey(up, 'Up')" },
      { t: "inheritance", d: "a class reusing another class's code", w: "W4", ex: "class Snake(Turtle):" },
      { t: "list of objects", d: "many objects stored in a list", w: "W4", ex: "self.segments = []" },
      { t: "collision detection", d: "checking if two things touch", w: "W5", ex: "if head.distance(food) < 15:" },
      { t: "refactor", d: "rewrite code cleaner without changing behavior", w: "W5", ex: "split into methods" },
      { t: "scoreboard", d: "an object that tracks and shows score", w: "W6", ex: "self.score = 0" },
      { t: "difficulty", d: "the game getting harder over time", w: "W7", ex: "speed += 1" },
      { t: "open()", d: "open a file to read or write", w: "W8", ex: 'open("notes.txt", "w")' },
      { t: "with statement", d: "open a file and auto-close it", w: "W8", ex: "with open(f) as file:" },
      { t: "csv", d: "comma-separated values data file", w: "W9", ex: "import csv" },
      { t: "list comprehension", d: "build a list in one short line", w: "W10", ex: "[x*2 for x in nums]" },
      { t: "zip()", d: "pair items from two lists together", w: "W10", ex: "zip(letters, codes)" },
      { t: "tkinter", d: "Python's built-in window/GUI toolkit", w: "W11", ex: "import tkinter" },
      { t: "widget", d: "a UI piece: label, button, entry", w: "W11", ex: "Button(text='Go')" },
      { t: "command", d: "the function a button runs when clicked", w: "W11", ex: "Button(command=go)" },
      { t: ".after()", d: "run a function after N milliseconds", w: "W12", ex: "window.after(1000, tick)" },
      { t: "messagebox", d: "a popup dialog window", w: "W13", ex: "messagebox.showinfo(...)" },
      { t: "try / except", d: "catch an error so it won't crash", w: "W14", ex: "try:\n    ...\nexcept:\n    ..." },
      { t: "json", d: "a text format for saving structured data", w: "W14", ex: "json.dump(data, file)" },
      { t: "pandas", d: "a library for working with table data", w: "W15", ex: "import pandas" },
      { t: "datetime", d: "work with dates and times", w: "W16", ex: "datetime.now()" },
      { t: "smtplib", d: "send email from Python", w: "W16", ex: "import smtplib" },
    ],
  },
  {
    code: "BC003", title: "APIs & Automation", icon: "🌐", track: "Python Bootcamp · 100 Days",
    blurb: "Days 33–48. APIs, HTML/CSS, scraping, Selenium.",
    terms: [
      { t: "API", d: "a way for programs to talk to a service", w: "W1", ex: "weather API" },
      { t: "requests", d: "Python library to fetch data from the web", w: "W1", ex: "import requests" },
      { t: "GET request", d: "ask a server for data", w: "W1", ex: "requests.get(url)" },
      { t: "response", d: "what the server sends back", w: "W1", ex: "r = requests.get(url)" },
      { t: ".json()", d: "turn an API response into a Python dict", w: "W2", ex: "data = r.json()" },
      { t: "status code", d: "a number saying if the request worked", w: "W2", ex: "200 = OK, 404 = not found" },
      { t: "parameters", d: "extra options sent with a request", w: "W3", ex: "params={'q': 'Seoul'}" },
      { t: "API key", d: "a secret password for using an API", w: "W3", ex: "params={'key': KEY}" },
      { t: "POST request", d: "send data to a server", w: "W4", ex: "requests.post(url, json=d)" },
      { t: "JSON body", d: "the data you send in a POST", w: "W4", ex: "json={'score': 10}" },
      { t: "header", d: "extra info sent with a request (auth)", w: "W5", ex: "headers={'token': T}" },
      { t: "PUT request", d: "update existing data on a server", w: "W5", ex: "requests.put(url, json=d)" },
      { t: "environment variable", d: "a secret stored outside the code", w: "W6", ex: "os.environ['KEY']" },
      { t: "data manager", d: "a class that handles all API calls", w: "W7", ex: "class DataManager:" },
      { t: "notification", d: "an automatic alert (SMS/email)", w: "W8", ex: "send_sms('Deal!')" },
      { t: "HTML tag", d: "the label that names a web element", w: "W9", ex: "<h1>Title</h1>" },
      { t: "attribute", d: "extra info inside a tag", w: "W9", ex: '<a href="...">' },
      { t: "table / list", d: "HTML structures for rows or bullets", w: "W10", ex: "<ul><li>...</li></ul>" },
      { t: "CSS rule", d: "selector + style declarations", w: "W11", ex: "p { color: red; }" },
      { t: "class selector", d: "style every element with a class", w: "W12", ex: ".card { ... }" },
      { t: "BeautifulSoup", d: "library that reads HTML for you", w: "W13", ex: "soup = BeautifulSoup(html)" },
      { t: ".find()", d: "get the first matching HTML element", w: "W13", ex: "soup.find('h1')" },
      { t: "find_all()", d: "get every matching element as a list", w: "W14", ex: "soup.find_all('a')" },
      { t: ".text", d: "the visible text inside an element", w: "W14", ex: "tag.text" },
      { t: "parsing", d: "pulling structured data out of text", w: "W15", ex: "float(price.strip('$'))" },
      { t: "Selenium", d: "controls a real browser automatically", w: "W16", ex: "from selenium import webdriver" },
      { t: "find_element", d: "locate a thing on the web page", w: "W16", ex: "driver.find_element(...)" },
      { t: "send_keys", d: "type text into a web field", w: "W16", ex: "box.send_keys('hi')" },
    ],
  },
  {
    code: "BC004", title: "Flask & Safe Bots", icon: "🤖", track: "Python Bootcamp · 100 Days",
    blurb: "Days 49–64. Automation, Flask, Bootstrap, SQLAlchemy.",
    terms: [
      { t: "automation", d: "code doing a manual task for you", w: "W1", ex: "auto-fill a form" },
      { t: "find_element", d: "locate something on a web page", w: "W1", ex: "driver.find_element(...)" },
      { t: "loop automation", d: "repeating an action many times", w: "W2", ex: "for i in range(10): click()" },
      { t: "wait", d: "pause until the page is ready", w: "W2", ex: "time.sleep(2)" },
      { t: "log to file", d: "save a record of what happened", w: "W3", ex: 'open("log.txt", "a")' },
      { t: "dictionary tally", d: "count things using a dict", w: "W4", ex: "counts[name] += 1" },
      { t: "iterate rows", d: "loop through each row of data", w: "W5", ex: "for row in rows:" },
      { t: "Flask", d: "a Python framework for websites", w: "W6", ex: "from flask import Flask" },
      { t: "route", d: "a URL the app responds to", w: "W6", ex: '@app.route("/")' },
      { t: "decorator", d: "the @ line that adds behavior", w: "W6", ex: "@app.route(...)" },
      { t: "app.run()", d: "start the web server", w: "W6", ex: "app.run(debug=True)" },
      { t: "route variable", d: "a changing part of the URL", w: "W7", ex: '@app.route("/<int:n>")' },
      { t: "return HTML", d: "the text/page a route sends back", w: "W8", ex: 'return "<h1>Hi</h1>"' },
      { t: "render_template", d: "show an HTML template file", w: "W9", ex: 'render_template("index.html")' },
      { t: "Jinja", d: "template language for variables in HTML", w: "W9", ex: "{{ name }}" },
      { t: "Bootstrap", d: "a ready-made CSS style library", w: "W10", ex: '<link href="bootstrap.css">' },
      { t: "component", d: "a reusable styled UI block", w: "W11", ex: '<div class="card">' },
      { t: "template inheritance", d: "pages sharing one base layout", w: "W11", ex: "{% extends 'base.html' %}" },
      { t: "form method POST", d: "send form data to the server", w: "W12", ex: '<form method="POST">' },
      { t: "request.form", d: "read submitted form data in Flask", w: "W12", ex: "request.form['name']" },
      { t: "WTForms", d: "a library that builds & checks forms", w: "W13", ex: "class LoginForm(FlaskForm):" },
      { t: "validator", d: "a rule a form field must pass", w: "W13", ex: "DataRequired()" },
      { t: "read CSV", d: "load rows from a CSV file", w: "W14", ex: "csv.reader(file)" },
      { t: "database", d: "organized storage for app data", w: "W15", ex: "movies table" },
      { t: "SQLAlchemy", d: "use a database with Python classes", w: "W15", ex: "class Movie(db.Model):" },
      { t: "query", d: "ask the database for data", w: "W15", ex: "Movie.query.all()" },
      { t: "CRUD", d: "Create, Read, Update, Delete data", w: "W16", ex: "add / view / edit / delete" },
      { t: "order_by", d: "sort database results", w: "W16", ex: "query.order_by(Movie.rating)" },
    ],
  },
  {
    code: "BC005", title: "Data Science", icon: "📊", track: "Python Bootcamp · 100 Days",
    blurb: "Days 65–80. REST, auth, deploy, pandas, regression.",
    terms: [
      { t: "UX", d: "how easy/pleasant a site is to use", w: "W1", ex: "clear buttons, good spacing" },
      { t: "REST", d: "a standard style for web APIs", w: "W2", ex: "GET / POST / PUT / DELETE" },
      { t: "jsonify", d: "send a Python dict back as JSON", w: "W3", ex: "return jsonify(data)" },
      { t: "endpoint", d: "one URL the API responds to", w: "W3", ex: "/api/posts" },
      { t: "hashing", d: "scramble a password so it's safe to store", w: "W4", ex: "generate_password_hash(pw)" },
      { t: "session", d: "remembering a logged-in user", w: "W4", ex: "session['user'] = id" },
      { t: "authentication", d: "checking who a user is", w: "W5", ex: "login_required" },
      { t: "relationship", d: "a link between two database tables", w: "W5", ex: "user.posts" },
      { t: "deploy", d: "put the app live on the internet", w: "W6", ex: "git push to host" },
      { t: "requirements.txt", d: "the list of libraries the app needs", w: "W6", ex: "flask\npandas" },
      { t: "pandas", d: "library for table (spreadsheet) data", w: "W7", ex: "import pandas as pd" },
      { t: "DataFrame", d: "a table of rows and columns", w: "W7", ex: "df = pd.read_csv('x.csv')" },
      { t: "read_csv", d: "load a CSV file into a DataFrame", w: "W7", ex: "pd.read_csv('data.csv')" },
      { t: "matplotlib", d: "library for drawing charts", w: "W8", ex: "import matplotlib.pyplot as plt" },
      { t: "plot", d: "draw a chart of data", w: "W8", ex: "plt.plot(x, y)" },
      { t: "groupby", d: "group rows and summarize them", w: "W9", ex: "df.groupby('year')" },
      { t: "merge", d: "join two DataFrames together", w: "W9", ex: "pd.merge(a, b)" },
      { t: "NaN", d: "a missing / empty value", w: "W10", ex: "df.dropna()" },
      { t: "plotly", d: "library for interactive charts", w: "W11", ex: "import plotly.express" },
      { t: "numpy", d: "library for fast number arrays", w: "W12", ex: "import numpy as np" },
      { t: "array", d: "a fast grid of numbers", w: "W12", ex: "np.array([1, 2, 3])" },
      { t: "scikit-learn", d: "library for machine learning models", w: "W13", ex: "from sklearn... import" },
      { t: "model.fit()", d: "train a model on data", w: "W13", ex: "model.fit(X, y)" },
      { t: "predict()", d: "use a trained model to guess", w: "W13", ex: "model.predict(X)" },
      { t: "EDA", d: "exploring data to find patterns", w: "W14", ex: "df.describe()" },
      { t: "p-value", d: "how likely a result is just chance", w: "W15", ex: "p < 0.05 = significant" },
      { t: "correlation", d: "how two things move together", w: "W15", ex: "df.corr()" },
      { t: "train/test split", d: "hold back data to test the model", w: "W16", ex: "train_test_split(X, y)" },
      { t: "features", d: "the input columns used to predict", w: "W16", ex: "X = df[['size','rooms']]" },
    ],
  },
  {
    code: "BC006", title: "Pro Projects", icon: "🚀", track: "Python Bootcamp · 100 Days",
    blurb: "Days 81–96. Showcase builds across everything learned.",
    terms: [
      { t: "dictionary mapping", d: "look one thing up to get another", w: "W1", ex: "MORSE['A']   # '.-'" },
      { t: ".upper()", d: "change letters to uppercase", w: "W1", ex: '"abc".upper()' },
      { t: "deploy", d: "put a site live on the internet", w: "W2", ex: "push to GitHub Pages" },
      { t: "2D list", d: "a list of lists (a grid)", w: "W3", ex: "[[0,0,0],[0,0,0]]" },
      { t: "win check", d: "logic that decides if someone won", w: "W3", ex: "if row all == 'X':" },
      { t: "Pillow", d: "library for editing images", w: "W4", ex: "from PIL import Image" },
      { t: "paste", d: "place one image onto another", w: "W4", ex: "img.paste(logo, (10,10))" },
      { t: "timer", d: "tracking elapsed time", w: "W5", ex: "time.time()" },
      { t: "WPM", d: "words per minute (typing speed)", w: "W5", ex: "words / minutes" },
      { t: "class", d: "a blueprint for game objects", w: "W6", ex: "class Ball:" },
      { t: "bricks list", d: "many objects stored in a list", w: "W6", ex: "bricks = [...]" },
      { t: "render_template", d: "Flask shows an HTML page", w: "W7", ex: "render_template('x.html')" },
      { t: "state", d: "the data describing the app right now", w: "W8", ex: "todos = []" },
      { t: "persistence", d: "saving data so it survives a restart", w: "W8", ex: "save to file" },
      { t: "countdown", d: "a timer that ticks down", w: "W9", ex: "window.after(1000, tick)" },
      { t: "PyPDF2", d: "library that reads PDF files", w: "W10", ex: "from PyPDF2 import PdfReader" },
      { t: "text-to-speech", d: "computer reading text aloud", w: "W10", ex: "import pyttsx3" },
      { t: "RGB tuple", d: "a color as (red, green, blue)", w: "W11", ex: "(255, 120, 73)" },
      { t: "pagination", d: "looping through multiple pages", w: "W12", ex: "for page in range(1, 6):" },
      { t: "Selenium", d: "controls a real browser automatically", w: "W13", ex: "from selenium import webdriver" },
      { t: "game loop", d: "the loop that keeps a game running", w: "W14", ex: "while running:" },
      { t: "enemy list", d: "all enemies stored in a list", w: "W14", ex: "enemies = [...]" },
      { t: "API site", d: "a web app that shows live API data", w: "W15", ex: "requests.get(api)" },
      { t: "cart", d: "items a user wants to buy", w: "W16", ex: "session['cart'] = []" },
      { t: "checkout", d: "the final pay/confirm step", w: "W16", ex: "total = sum(prices)" },
    ],
  },

  // ───────────────────────── MINECRAFT · CODE BUILDER ─────────────────────────
  // Courses run in both MakeCode blocks and Python. Examples use the Python style.
  {
    code: "MC000", title: "Builder Basics", icon: "🏗️", track: "Minecraft · Code Builder",
    blurb: "Move the agent, then build a bridge, house, well, and village.",
    terms: [
      { t: "agent", d: "the robot helper your code controls", w: "W1", ex: "agent.move(FORWARD, 1)" },
      { t: "on_chat", d: "run code when you type a chat word", w: "W1", ex: 'player.on_chat("go", run)' },
      { t: "agent.move", d: "move the agent one block in a direction", w: "W1", ex: "agent.move(FORWARD, 1)" },
      { t: "direction", d: "FORWARD / BACK / LEFT / RIGHT / UP / DOWN", w: "W1", ex: "agent.move(LEFT, 2)" },
      { t: "agent.turn", d: "rotate the agent left or right", w: "W1", ex: "agent.turn(RIGHT)" },
      { t: "agent.place", d: "put down the block the agent holds", w: "W2", ex: "agent.place(DOWN)" },
      { t: "block type", d: "which block to use (GRASS, STONE…)", w: "W2", ex: "agent.set_item(STONE, 1, 1)" },
      { t: "agent slot", d: "the inventory box the agent builds from", w: "W2", ex: "agent.set_slot(1)" },
      { t: "sequence", d: "steps that run in order, top to bottom", w: "W3", ex: "move(); place(); move()" },
      { t: "loop", d: "repeat steps without retyping them", w: "W3", ex: "for i in range(5):" },
      { t: "range()", d: "how many times the loop repeats", w: "W3", ex: "range(5)   # 0..4" },
      { t: "four sides", d: "turn 90° four times to make a square", w: "W4", ex: "for i in range(4):\n    wall()" },
      { t: "wall", d: "a line of blocks built with a loop", w: "W4", ex: "for i in range(6): agent.place(DOWN)" },
      { t: "layer", d: "one flat level of the build", w: "W5", ex: "build_layer()" },
      { t: "UP / height", d: "stack layers to add height", w: "W5", ex: "agent.move(UP, 1)" },
      { t: "dig DOWN", d: "destroy/clear blocks downward", w: "W6", ex: "agent.destroy(DOWN)" },
      { t: "depth", d: "how many blocks deep you go", w: "W6", ex: "for i in range(4): dig()" },
      { t: "grid", d: "rows and columns of blocks", w: "W7", ex: "for r in range(5):\n    for c in range(5):" },
      { t: "function", d: "a named, reusable set of build steps", w: "W8", ex: "def build_house():" },
      { t: "coordinates", d: "an (x, y, z) spot in the world", w: "W8", ex: "blocks.place(OAK, world(0,0,0))" },
      { t: "reuse", d: "call the same function many times", w: "W8", ex: "build_house(); build_house()" },
    ],
  },
  {
    code: "MC001", title: "Pyramid Problems", icon: "🔺", track: "Minecraft · Code Builder",
    blurb: "From a one-line path to a full diamond structure with loops & variables.",
    terms: [
      { t: "agent", d: "the robot helper your code controls", w: "W1", ex: "agent.move(FORWARD, 1)" },
      { t: "instruction", d: "one command you give the agent", w: "W1", ex: "agent.place(DOWN)" },
      { t: "run", d: "make the code happen in the world", w: "W1", ex: 'player.on_chat("start", go)' },
      { t: "loop", d: "repeat code instead of retyping it", w: "W2", ex: "for i in range(8):" },
      { t: "repeat", d: "do the same block N times", w: "W2", ex: "for i in range(8): place()" },
      { t: "iteration", d: "one pass through the loop", w: "W2", ex: "# each i = one block" },
      { t: "variable", d: "a named box that holds a value", w: "W3", ex: "size = 5" },
      { t: "value", d: "the data stored in the variable", w: "W3", ex: "size = 5   # value is 5" },
      { t: "reuse value", d: "use one variable in many places", w: "W3", ex: "range(size)" },
      { t: "nested loop", d: "a loop inside another loop", w: "W4", ex: "for r in range(3):\n    for c in range(3):" },
      { t: "outer / inner", d: "outer = rows, inner = each block in a row", w: "W4", ex: "outer rows, inner cols" },
      { t: "indentation", d: "spaces that show what's inside a loop", w: "W4", ex: "for i in range(3):\n    place()" },
      { t: "layer width", d: "each pyramid layer is smaller", w: "W5", ex: "range(size - level)" },
      { t: "step", d: "the change between layers", w: "W5", ex: "level += 1" },
      { t: "range step", d: "count up or down by an amount", w: "W6", ex: "range(5, 0, -1)" },
      { t: "reverse", d: "flip the order to invert the shape", w: "W6", ex: "for i in range(5, 0, -1):" },
      { t: "parameter", d: "an input that changes the build size", w: "W7", ex: "def pyramid(size):" },
      { t: "generalize", d: "one function that builds any size", w: "W7", ex: "pyramid(7)" },
      { t: "combine", d: "join two builds into one", w: "W8", ex: "pyramid_up(); pyramid_down()" },
      { t: "mirror", d: "a shape repeated upside-down", w: "W8", ex: "# top + flipped bottom" },
      { t: "plan", d: "decide the steps before coding", w: "W8", ex: "# 1 base 2 layers 3 tip" },
    ],
  },
  {
    code: "MC002", title: "Maze Madness", icon: "🌀", track: "Minecraft · Code Builder",
    blurb: "Maze logic with conditions and redstone. (Weeks 1–5; W6–8 in preparation.)",
    terms: [
      { t: "condition", d: "a question that is true or false", w: "W1", ex: "if signal == LEFT:" },
      { t: "if", d: "run code only when a condition is true", w: "W1", ex: "if turn_left:\n    agent.turn(LEFT)" },
      { t: "signal", d: "an input that says which way to go", w: "W1", ex: "L / R / U / D" },
      { t: "react", d: "the action taken for a signal", w: "W1", ex: "if s == UP: agent.move(UP,1)" },
      { t: "if / else", d: "one path if true, another if false", w: "W2", ex: "if door: open()\nelse: wait()" },
      { t: "mapping", d: "each input leads to one action", w: "W2", ex: "L→left, R→right" },
      { t: "test", d: "try a rule and check it works", w: "W2", ex: "# type 'L', agent goes left" },
      { t: "and", d: "true only when BOTH are true", w: "W3", ex: "if a and b:" },
      { t: "multiple conditions", d: "check more than one thing at once", w: "W3", ex: "if red and lever:" },
      { t: "combine logic", d: "join conditions into one rule", w: "W3", ex: "if x and y and z:" },
      { t: "elif", d: "check another condition if the first fails", w: "W4", ex: "if a:\n  ..\nelif b:\n  .." },
      { t: "or", d: "true when AT LEAST ONE is true", w: "W4", ex: "if a or b:" },
      { t: "priority", d: "which condition is checked first", w: "W4", ex: "if danger: stop()" },
      { t: "decision tree", d: "a chain of if / elif / else choices", w: "W4", ex: "if .. elif .. else .." },
      { t: "redstone", d: "Minecraft's wiring that carries power", w: "W5", ex: "blocks.place(REDSTONE, p)" },
      { t: "power", d: "a redstone signal that is on or off", w: "W5", ex: "on = True" },
      { t: "lever / button", d: "a switch that turns power on/off", w: "W5", ex: "blocks.place(LEVER, p)" },
      { t: "trigger", d: "the event that opens the door", w: "W5", ex: "if powered: open_door()" },
    ],
  },
];
